import { StyleSheet } from "react-native";
const Spacing = StyleSheet.create({
    p10:{
        padding:10
    },
    p20:{
        padding:20
    },
    p30:{
        padding:30
    },
    p40:{
        padding:40
    },
    p50:{
        padding:50
    },
    p60:{
        padding:60
    },
    p70:{
        padding:70
    },
    p80:{
        padding:80
    },
    p90:{
        padding:90
    },
    p100:{
        padding:100
    },
    mt5:{
        marginTop:5
    },
    mt10:{
        marginTop:10
    },
    mb5:{
        marginBottom:5
    },
    mb10:{
        marginBottom:10
    },
    ml5:{
        marginLeft:5
    },
    ml10:{
        marginLeft:10
    },
    ml20:{
        marginLeft:20
    },
    mr5:{
        marginRight:5
    },
    mr10:{
        marginRight:10
    },
    mr20:{
        marginRight:20
    },
    mr15:{
        marginRight:15
    },
    mb20:{
        marginBottom:20
    },
    mt15:{
        marginTop:15
    },
    mt20:{
        marginTop:20
    },
    pt5:{
        paddingTop:5
    },
    pt10:{
        paddingTop:10
    },
    pt20:{
        paddingTop:20
    },
    plr5:{
        paddingLeft:5,
        paddingRight:5
    },
    plr10:{
        paddingLeft:10,
        paddingRight:10
    },
    plr20:{
        paddingLeft:20,
        paddingRight:20
    },
    plr30:{
        paddingLeft:30,
        paddingRight:30
    },
    pb5:{
        paddingBottom:5
    },
    pb10:{
        paddingBottom:10
    },
    pb20:{
        paddingBottom:20
    },
    p15:{
        padding:15
    },
    topScreenBorder:{
        borderTopLeftRadius : 30 , 
        borderTopRightRadius : 30
    }
    
})
export default Spacing;